name: river_egg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - jupyter
  - ipykernel
  - matplotlib
  - folium
  - pandas
  - numpy
  - fiona
  - contextily
  - ipywidgets
  - mapclassify
  - geopy
  - scikit-learn
  - requests
  - earthaccess